#!/usr/bin/bash

check_factor() {
    if [ $# -ne 3 ]; then
        num2=$(echo "${@:2}" | tr ' ' '*' | bc)
    else
        num2=$3
    fi

    num1=$2
    num=$(echo "$1" | tr ':' '=')

    if ((num2 > num1)); then
        numcp=$num1
        num1=$num2
        num2=$numcp
    fi

    echo "$num$num1*$num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
else
    while read -r i; do
        result=$(factor "$i")
        check_factor $result
    done < "$1"
fi
